#!/usr/bin/env python3
"""
plot_fisher_diagnostics.py

Visualizes the Fisher-information diagnostic data generated by
``reproduce_fisher_diagnostics_data.py``.

The script reads previously generated JSON datasets from the
``reproduction_data/`` directory and produces the three diagnostic plots
used to analyse the scaling behaviour of the classical Fisher information
in the multi-time measurement protocol.

The plotting routine automatically discovers all available datasets,
classifies them by experiment type, and aggregates results across
Hamiltonian families where appropriate.

Generated figures
-----------------

The script produces three diagnostic plots:

1. **Fisher trace scaling vs total experiment time**

   Displays the scaling of the Fisher-information trace

       Tr(I)

   as a function of the total experiment time

       T_tot = Σ_k t_k

   for different spread-state ensemble sizes R.

   Each curve corresponds to one ensemble size R and is fitted with a
   power law

       Tr(I) = A T_tot^p.

   This plot is generated for a **single selected Hamiltonian family**
   (specified via ``--family``).

2. **Scaling exponent vs spread-state ensemble size**

   Displays the fitted cumulative Fisher scaling exponent

       p

   as a function of the number of spread states

       R.

   Results from all Hamiltonian families are shown together.

3. **Scaling exponent vs scheduling parameter**

   Displays the dependence of the fitted exponent

       p(R=1)

   on the time-scheduling parameter α.

   The numerical results are compared to the theoretical prediction

       p = (α γ₀ + 1) / (α + 1)

   with γ₀ = 2, corresponding to quadratic short-time Fisher scaling.

   Data from all Hamiltonian families are shown together.

Data discovery
--------------

The script recursively searches the data directory for files of the form

    fisher_trace_scaling_*_all_alphas.json

and automatically determines whether they belong to:

• fixed-α / varying-R experiments  
• fixed-R=1 / varying-α experiments

based on the structure of the stored data.

Usage
-----

Run the plotting script after generating the datasets:

    python plot_fisher_diagnostics.py

Optionally specify:

    --data-dir   path to the reproduction_data directory
    --family     Hamiltonian family used for the first plot

Example:

    python plot_fisher_diagnostics.py --family XYZ

Notes
-----

Figures are displayed interactively and are not written to disk.
This script is intended for exploratory visualization and reproduction
of the diagnostic figures from the stored datasets.
"""


import os
import shutil
from fisher_diagnostics import run_fisher_diagnostic


def ensure_dir(path: str, clean: bool = False) -> None:
    if clean and os.path.isdir(path):
        shutil.rmtree(path)
    os.makedirs(path, exist_ok=True)


def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_root = os.path.join(base_dir, "reproduction_data")
    ensure_dir(output_root, clean=False)

    common = dict(
        num_qubits=5,
        delta_t=0.01,
        steps=[2, 4, 6, 8, 10],
        measurements=25,
        shots=1,
        seed=99901,
        max_batch=16,
        max_outcomes=None,
    )

    families = ["XYZ", "XYZ2", "XYZ3", "XXYGL"]

    # Experiment A: fixed alpha, vary R
    expA_root = os.path.join(output_root, "expA_fixed_alpha_vary_R")
    os.makedirs(expA_root, exist_ok=True)

    print("==================== Fisher Diagnostics Run 1/2 ====================")
    for family in families:
        family_out = os.path.join(expA_root, family)
        ensure_dir(family_out, clean=True)

        run_fisher_diagnostic(
            family=family,
            alphas=[1.0],
            spreadings=[1, 2, 4, 8, 16],
            output_root=family_out,
            **common,
        )
        
    print("==================== Fisher Diagnostics Run 2/2 ====================")

    # Experiment B: fixed R=1, vary alpha
    expB_root = os.path.join(output_root, "expB_fixed_R1_vary_alpha")
    os.makedirs(expB_root, exist_ok=True)

    for family in families:
        family_out = os.path.join(expB_root, family)
        ensure_dir(family_out, clean=True)

        run_fisher_diagnostic(
            family=family,
            alphas=[0.2, 0.4, 0.6, 0.8, 1.0],
            spreadings=[1],
            output_root=family_out,
            **common,
        )

    print(f"Reproduced data written to: {output_root}")


if __name__ == "__main__":
    main()